# Generated by Django 3.2.16 on 2022-11-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_auto_20221105_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cid',
            new_name='cat_id',
        ),
    ]
