# Generated by Django 3.2.16 on 2022-11-05 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_rename_cid_category_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default=datetime.timezone, max_length=15, null=True),
        ),
    ]
