# Generated by Django 3.2.16 on 2022-11-05 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_auto_20221105_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.UUIDField(default=uuid.UUID('122ef3e2-bb64-4b6c-b3cb-a6bd58cfc13b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
