# Generated by Django 3.2.16 on 2022-11-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default=None, upload_to='photos/categories'),
        ),
    ]
